version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_monthly:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2017-04-01 to 2022-04-01 by month" --output-dir=output/monthly --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/monthly/input_*.csv.gz

  generate_study_population_weekly:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-04-01 to 2022-04-01 by week" --output-dir=output/weekly --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/weekly/input_*.csv.gz

  generate_study_population_dob:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_dob --output-dir=output --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_dob.csv.gz